apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
      annotations:
        kubearmor-policy: wisecow-zero-trust   # <- attach policy here
    spec:
      containers:
      - name: wisecow
        image: saihari1/wisecow:new
        ports:
        - containerPort: 4499
        imagePullPolicy: Always

